# consorcio-frontend/Dockerfile.dev
FROM node:20-alpine

ARG USER=node

# criar user somente se nao existir (evita erro se 'node' já existe)
RUN if ! id -u ${USER} >/dev/null 2>&1 ; then \
      addgroup -S ${USER} && adduser -S ${USER} -G ${USER} ; \
    fi

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 4200

# usar user não-root (se existir)
USER ${USER}

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
