FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 4200

# HOST=0.0.0.0 permite acessar via navegador local
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
